/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ungoverned_osgi_bundle_simple_SimpleBundle */

#ifndef _Included_org_ungoverned_osgi_bundle_simple_SimpleBundle
#define _Included_org_ungoverned_osgi_bundle_simple_SimpleBundle
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: class_00024javax_00024servlet_00024http_00024HttpSession */
/* Inaccessible static: class_00024javax_00024servlet_00024Servlet */
/*
 * Class:     org_ungoverned_osgi_bundle_simple_SimpleBundle
 * Method:    foo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ungoverned_osgi_bundle_simple_SimpleBundle_foo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
